"""Generate the PyInstaller VSVersionInfo file for FlowBooks.exe (issue #106).

The frozen exe carried no version resource, so Properties → Details and
inventory tools (SCCM/Intune/Lansweeper) read nothing; only the Inno
installer knew the version. The spec writes this file next to itself at
build time from app/__init__.py and passes it as EXE(version=...).
Kept import-free of the app so the spec (and the tests) can call it
without booting anything.
"""

from __future__ import annotations

import re
from pathlib import Path

PRODUCT_NAME = "FlowBooks"
COMPANY_NAME = "VonHoltenCodes"
INTERNAL_NAME = "FlowBooks"
ORIGINAL_FILENAME = "FlowBooks.exe"
DESCRIPTION = "FlowBooks — bookkeeping"
COPYRIGHT = "Copyright (c) 2026 Trent Von Holten. Source Available License, version 2.0."


def read_version(app_init: Path) -> str:
    m = re.search(
        r'^__version__\s*=\s*"([^"]+)"', app_init.read_text(encoding="utf-8"), re.M
    )
    if not m:
        raise ValueError(f"no __version__ in {app_init}")
    return m.group(1)


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """'2.10.0' → (2, 10, 0, 0); a pre-release suffix ('2.10.0rc1') keeps the
    numeric part — the resource holds four 16-bit integers only."""
    nums = [int(x) for x in re.findall(r"\d+", version)[:4]]
    while len(nums) < 4:
        nums.append(0)
    return tuple(nums)  # type: ignore[return-value]


def render(version: str) -> str:
    fv = version_tuple(version)
    strings = [
        ("CompanyName", COMPANY_NAME),
        ("FileDescription", DESCRIPTION),
        ("FileVersion", version),
        ("InternalName", INTERNAL_NAME),
        ("LegalCopyright", COPYRIGHT),
        ("OriginalFilename", ORIGINAL_FILENAME),
        ("ProductName", PRODUCT_NAME),
        ("ProductVersion", version),
    ]
    table = ",\n".join(f"        StringStruct({k!r}, {v!r})" for k, v in strings)
    return f"""# Generated by packaging/windows/version_info.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fv!r},
    prodvers={fv!r},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
{table}
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def write(app_init: Path, out: Path) -> str:
    version = read_version(app_init)
    out.write_text(render(version), encoding="utf-8")
    return version


if __name__ == "__main__":  # pragma: no cover
    import sys

    here = Path(__file__).resolve().parent
    root = here.parent.parent
    v = write(root / "app" / "__init__.py", here / "version_info.txt")
    print(f"wrote {here / 'version_info.txt'} for {v}", file=sys.stderr)
